name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - uses: nttld/setup-ndk@v1
         with:
            ndk-version: r25b
            local-cache: true
       - name: set up JDK 11
         uses: actions/setup-java@v3
         with:
            java-version: '11'
            distribution: 'temurin'
            cache: gradle
       - name: dx fix
         run:  cp /usr/local/lib/android/sdk/build-tools/33.0.0/d8 /usr/local/lib/android/sdk/build-tools/33.0.0/dx; cp /usr/local/lib/android/sdk/build-tools/33.0.0/**/d8*  /usr/local/lib/android/sdk/build-tools/33.0.0/lib/dx
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
       - name: Build with Gradle
         run: ./gradlew build
